name: snippetbox

services:
  db:
    build:
      context: docker/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
